<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Time to Shine</title>
  <link rel="stylesheet" href="css/style.css" type="text/css">
</head>

<body>
  <div class="main">
    {% include 'header.phtml' %}
    
    <h1 class="name"><i>Jewellery  from <q>Time to Shine</q></i></h1><br>
    <p>Greetings! We're glad to see you on our website.<br>
      Please take a look on our products and chose what is more suitable for you.</p>
      
      {% include 'link.phtml' %}
    <img src="css/bril.GIF" height="500">

    {% include 'footer.phtml' %}
  </div>
</body>

</html>